### ISSUE TITLE
Performance concern

### ISSUE THREAD

**Issue by ronaldknol** [shirosaidev/diskover#1]
Hi Chris,

First of all, I think this is a great project. I like the way your visualized the data.

About 15 years ago I wrote my own "du" type program (in C) which was also multithreaded and custom for our studio. However, even multi-threaded with a large enough filesystem (~100TB with millions files in thousands of directories) the code would take more than 24 hours to run.
In production, it's not acceptable to have data/analytics that is old. You cannot make proper decisions if your disk usage data not current.

Have you tested your code against a large filesystem? It really doesn't matter what the capacity is, it's the number of files (and number of directories) that will determine how long your code takes to run (and a little bit the speed of the vendor's inode lookups). Even on a 10GB filesystem you can create (1KB sized) files in subdirectories and let your code walk it. Please post some benchmarks as those are critical in production environments.

Luckily the vendors are catching on (Qumulo) and the requirement for filesystem crawls should soon be a thing of the past. :)

**Comment by shirosaidev** [comment]
Hi Ronald, thanks for your feedback and I agree with you about the importance of having the data analytics current.

The command line options for Diskover should help speed up the crawl times such as setting minimum file size and modified time. Also excluding certain files/directories will help.

You could also speed up the crawl by running multiple Diskover processes and bulk loading into different diskover-<name> indices in Elasticsearch. I haven't tested this but in theory that should help to pull in data faster for analysis. Diskover bulk loads data into Elasticsearch while the crawl is running so you can view in Kibana during the scan.

Here are some benchmarks running on my macbook pro, this includes time to crawl my local filesystem and index in Elasticsearch. The files were all 1KB.

```
[2017-04-23 10:02:58] *** Processed Directories: 10001
[2017-04-23 10:02:58] *** Processed Files: 10000
[2017-04-23 10:02:58] *** Elapsed time: 16.2423961163

[2017-04-23 10:46:24] *** Processed Directories: 100001
[2017-04-23 10:46:24] *** Processed Files: 100000
[2017-04-23 10:46:24] *** Elapsed time: 167.5496099
```

**Comment by shirosaidev** [comment]
I've added these benchmarks and crawl tips to the readme.

**Comment by scr512** [comment]
Just to add some stats on a large project directory crawl running on bare metal with 20 threads:

`v1.0.10`
`[2017-05-16 02:52:40] [status] Connecting to Elasticsearch`
`[2017-05-16 02:52:40] [info] Checking for ES index: diskover-2017.05.16`
`[2017-05-16 02:52:40] [info] Creating ES index`
`Crawling: [100%]` 
`8768555/8768555`
`[2017-05-16 10:36:00] [status] Finished crawling`
`[2017-05-16 10:36:00] [info] Directories Crawled: 8768555`
`[2017-05-16 10:36:00] [info] Files Indexed: 1542891`
`[2017-05-16 10:36:00] [info] Elapsed time: 27800.2159569`

Stats for this project from our Isilon:

`type: directory`
 `AppliesTo: DEFAULT`
      `Path: /ifs/<withheld>`
      `Snap: No`
`Thresholds`
          `Hard: 90.00T`
          `Soft: -`
           `Adv: -`
         `Grace: -`
     `Usage`
            `Files: 98967237`
    `With Overhead: 80.90T`
     `W/O Overhead: 59.70T`

We called the following for the scan:
`diskover.py -d /$MOUNT -m 1 -s 1 -t 20 -i diskover-$INDEX`

**Comment by shirosaidev** [comment]
**v1.1.0** uses the faster python module os.scandir instead of os.listdir, would be interested to see your crawl times after using this new version.

**Comment by scr512** [comment]
Yup, I'm rerunning now... I'll update with results once it completes.

**Comment by shirosaidev** [comment]
**v1.1.1** which I released today has some bug fixes for file/directory exclusions if you were doing a lot of those.

**Comment by shirosaidev** [comment]
Also, Python3 is now supported by diskover which includes os.scandir since v3.5. If you are using Python2 you will need to pip install scandir.

**Comment by scr512** [comment]
Results with 1.1.0 - same dataset as before though there is some variance in this set as it's semi-active.
`./diskover.py -d $MOUNT -m 1 -s 1 -t 20 -i diskover-$INDEX`

`2017-06-23 10:41:16,585 [INFO][diskover] Finished crawling
2017-06-23 10:41:16,585 [INFO][diskover] Directories Crawled: 8510793
2017-06-23 10:41:16,585 [INFO][diskover] Files Indexed: 1563815
2017-06-23 10:41:16,585 [INFO][diskover] Elapsed time: 135833.142521`

Unsure why I'm seeing a performance regression here - Possible that the underpinning storage cluster was under duress when the scan was running.

I'll re run a couple of times to make sure there wasn't something else clouding these results.

**Comment by shirosaidev** [comment]
wow, thats a difference of close to 70 ms per file. Yes, if you can, please re-run again using v1.1.1 (latest). Thanks!

**Comment by shirosaidev** [comment]
still having crawl speed issues?

**Comment by shirosaidev** [comment]
Jason, are you using the new v1.5.0-rc versions? Would be curious to hear how your crawl times are these days.
