### ISSUE TITLE
Problem to start diskover "no module named pwd"

### ISSUE THREAD

**Issue by proteusos** [shirosaidev/diskover#15]
hi, i've got a problem to start your script. I followed the instructions and installed the requirements before. Then i cd into the folder i want to index and execute the python script. I used a win 10 system!

**Error in line 44 of diskover.py:**
import pwd
ModuleNotFoundError: No module named 'pwd'

i can't install pwd over pip...not existing. 
thanks

**Comment by rapphil** [comment]
pwd is a module available only on Unix like systems (like Linux or Mac OS). I'm afraid Diskover is not compatible with Windows at this point.
