### ISSUE TITLE
ElasticSearch 6.0 support

### ISSUE THREAD

**Issue by gourneau** [shirosaidev/diskover#19]
When trying to use Diskover 1.5.0 with ElasticSearch 6.0.1, I get this error. 

```
jgourneau@ghDsqlDEV03:~/esfs/diskover$ python diskover.py


      __               __
     /\ \  __         /\ \
     \_\ \/\_\    ____\ \ \/'\     ___   __  __     __   _ __     //
     /'_` \/\ \  /',__\\ \ , <    / __`\/\ \/\ \  /'__`\/\`'__\  ('>
    /\ \L\ \ \ \/\__, `\\ \ \\`\ /\ \L\ \ \ \_/ |/\  __/\ \ \/   /rr
    \ \___,_\ \_\/\____/ \ \_\ \_\ \____/\ \___/ \ \____\\ \_\  *\))_
     \/__,_ /\/_/\/___/   \/_/\/_/\/___/  \/__/   \/____/ \/_/ v1.5.0
                      https://shirosaidev.github.io/diskover
                      "Holy s*i# there are so many temp files."
                      Support diskover on Patreon or PayPal :)


2018-03-07 20:55:57,885 [INFO][diskover] Connecting to Elasticsearch
2018-03-07 20:56:06,093 [WARNING][diskover] Not running as root, you may not be able to crawl all files
2018-03-07 20:56:06,093 [INFO][diskover] Checking ES index: diskover-index
2018-03-07 20:56:06,129 [INFO][diskover] Creating ES index
2018-03-07 20:56:06,177 [WARNING][elasticsearch] PUT https://url:443/diskover-index [status:400 request:0.047s]
Traceback (most recent call last):
  File "diskover.py", line 2860, in <module>
    index_create(CLIARGS['index'])
  File "diskover.py", line 1835, in index_create
    ES.indices.create(index=indexname, body=mappings)
  File "/mnt/biodesk/software/anaconda/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/mnt/biodesk/software/anaconda/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 107, in create
    params=params, body=body)
  File "/mnt/biodesk/software/anaconda/lib/python3.5/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/mnt/biodesk/software/anaconda/lib/python3.5/site-packages/elasticsearch/connection/http_requests.py", line 90, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/mnt/biodesk/software/anaconda/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Rejecting mapping update to [diskover-index] as the final mapping would have more than 1 type: [file, crawlstat, diskspace, directory]')
```

The same command and config upload to a ES 5.5 cluster with no issues.

**Comment by gourneau** [comment]
Notes at the single mapping types https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html

**Comment by shirosaidev** [comment]
diskover does not currently support ES 6.

**Comment by victorhooi** [comment]
@shirosaidev Is there a tracking ticket for ES 6 support in Diskover?

**Comment by shirosaidev** [comment]
@victorhooi no plans currently to get diskover working with ES 6 until maybe after final release of 1.5.0.

**Comment by LordBonkerz** [comment]
Hello! :)  cool project...... Any news on version 6  support?

**Comment by jessestuart** [comment]
@LordBonkerz ...or ES7 for that matter? There were some hiccups in early releases, but v7.3.0 was [recently released](https://www.elastic.co/guide/en/elasticsearch/reference/7.3/release-notes-7.3.0.html) (~1wk ago), and so far I've had it running without issue in production.

Just wondering if it makes sense to update to an already-outdated version — v5.x was [already EOL'd](https://www.elastic.co/support/eol) in 2019 March, while the latest 7.3.0 will be supported until 2021. 

@shirosaidev, you proposed holding off until the 1.5 release of `diskover`, which I see [went GA](https://github.com/shirosaidev/diskover/blob/master/CHANGELOG.md#1501---2019-07-02) a little over a month ago. Would this be a good time to revisit this question? If you're open to it, I think creating a new umbrella issue with low-hanging-fruit / action-items would allow contributors to assess what needs to be done and get the ball rolling on this. 🚀

Thoughts?

**Comment by shirosaidev** [comment]
fyi, to update everyone about this, es 7.x support is being worked on by me... hopefully released in September sometime...

**Comment by voltagex** [comment]
@shirosaidev how's it going? Anything that other developers can help with? Is there a dev branch somewhere?

**Comment by maximd** [comment]
AFAIK, elasticsearch 7 is available but in the enterprise version: https://diskoverspace.com/#compare

**Comment by mareban** [comment]
Which september :-)  ??

**Comment by q2dg** [comment]
> AFAIK, elasticsearch 7 is available but in the enterprise version: https://diskoverspace.com/#compare

Good bye, then, to this trap

**Comment by victorhooi** [comment]
@shirosaidev Just checking - is the ElasticSearch 5.x limitation for the community thing just a temporary thing, or is that a permanent thing?

As in, will the community DiskOver be updated to support the current ElasticSearch version at some point?

**Comment by shirosaidev** [comment]
Eventually I'm hoping to put these updates for es7 into the community edition, this is not to force people to buy diskover enterprise (@q2dg comment above), just it comes down to my available time and motivation and hopefully some additional sponsors of the community project to update the code

**Comment by LordBonkerz** [comment]
shame its not CE from the beginning! with ES7 support :(

**Comment by lenucksi** [comment]
> Eventually I'm hoping to put these updates for es7 into the community edition, this is not to force people to buy diskover enterprise (@q2dg comment above), just it comes down to my available time and motivation and hopefully some additional sponsors of the community project to update the code

Hey @shirosaidev, 
thanks for providing this great tool! :D 
Could you possibly outline what work would be needed for the migration to ES7? Maybe that will make it easier for possible sponsors of work / contributors to judge whether they want to try to tackle that work?

**Comment by torsdag** [comment]
We did a quick patch to get it to work with es7, been running it for a few months and works for our current purposes. 

https://github.com/ilpvfx/diskover/tree/ilp
https://github.com/ilpvfx/diskover-web/tree/ilp

cheers
