### ISSUE TITLE
0 Files Indexed and Nothing Showing in Kibana

### ISSUE THREAD

**Issue by CopyRunStart** [shirosaidev/diskover#2]
OS: Ubuntu 16.04.
Latest Elasticsearch, Kibana, Python, etc.
Searching an RO NFS Mount.

Here is my output:

```
python /diskover/diskover.py
[2017-04-26 13:37:27] *** Checking for ES index
[2017-04-26 13:37:27] *** ES index exists, deleting
[2017-04-26 13:37:27] *** Creating ES index
[2017-04-26 13:37:27] *** Starting crawl
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/diskover/diskover.py", line 169, in processDirectoryWorker
    filelist = crawlFiles(path, DATEEPOCH, DAYS, MINSIZE, EXCLUDED_FILES, VERBOSE)
  File "/diskover/diskover.py", line 122, in crawlFiles
    owner = null
NameError: global name 'null' is not defined

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/diskover/diskover.py", line 169, in processDirectoryWorker
    filelist = crawlFiles(path, DATEEPOCH, DAYS, MINSIZE, EXCLUDED_FILES, VERBOSE)
  File "/diskover/diskover.py", line 122, in crawlFiles
    owner = null
NameError: global name 'null' is not defined

[2017-04-26 13:38:08] *** Main thread waiting
[2017-04-26 13:38:08] *** Done
[2017-04-26 13:38:08] *** Directories Crawled: 4168
[2017-04-26 13:38:08] *** Files Indexed: 0
[2017-04-26 13:38:08] *** Elapsed time: 41.3652939796
```

**Comment by CopyRunStart** [comment]
Did I do something wrong to provoke:

`NameError: global name 'null' is not defined`

**Comment by shirosaidev** [comment]
I updated Diskover today with some bug fixes and some code changes for getting user/group info. I've added some nicer console output and verbose logging as well. Please update and let me know if you still see this.

**Comment by CopyRunStart** [comment]
Thanks.  

For starters, I might have been using Python 3.x which is my fault.

Spun up a fresh instance of Ubuntu 16.04 with Python 2.7 and everything else latest version including diskover.  

`[2017-04-27 12:11:20] [status] Connecting to Elasticsearch
[2017-04-27 12:11:20] [info] Checking for ES index
[2017-04-27 12:11:20] [warning] ES index exists, deleting
[2017-04-27 12:11:20] [info] Creating ES index
[2017-04-27 12:11:20] [status] Finding directories to crawl
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/diskover/diskover.py", line 254, in processDirectoryWorker
    indexAdd(ES, INDEXNAME, filelist, VERBOSE)
  File "/root/diskover/diskover.py", line 353, in indexAdd
    helpers.bulk(ES, filelist, index=INDEXNAME, doc_type='file')
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 194, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'9 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBt', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868408) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@47f27f51; line: 1, column: 323]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBu', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868409) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@52c7600b; line: 1, column: 349]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBv', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868407) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@62ea3826; line: 1, column: 321]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBw', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868410) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2cb28d5c; line: 1, column: 331]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBx', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868411) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@46aab51; line: 1, column: 327]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBy', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868412) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@17c6de53; line: 1, column: 323]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbBz', u'error': {u'caused_by': {u'reason': u'Numeric value (112209271115) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@122ea06c; line: 1, column: 321]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbB0', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868383) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@332b59c8; line: 1, column: 343]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl37j6xDPJklVbB1', u'error': {u'caused_by': {u'reason': u'Numeric value (112192508432) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@74dafd75; line: 1, column: 326]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}])

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/diskover/diskover.py", line 254, in processDirectoryWorker
    indexAdd(ES, INDEXNAME, filelist, VERBOSE)
  File "/root/diskover/diskover.py", line 353, in indexAdd
    helpers.bulk(ES, filelist, index=INDEXNAME, doc_type='file')
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 194, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: (u'12 document(s) failed to index.', [{u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB2', u'error': {u'caused_by': {u'reason': u'Numeric value (112187868413) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1ce53a4d; line: 1, column: 388]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB3', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339032) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@428c725c; line: 1, column: 359]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB4', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339033) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3a8ad008; line: 1, column: 365]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB5', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339034) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2b2de285; line: 1, column: 375]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB6', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339035) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@1d35a50e; line: 1, column: 362]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB7', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339036) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@217f0fae; line: 1, column: 361]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB8', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339037) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@789f72a3; line: 1, column: 374]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB9', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339038) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@7210cf63; line: 1, column: 357]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB-', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339039) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@2562d72b; line: 1, column: 350]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbB_', u'error': {u'caused_by': {u'reason': u'Numeric value (125028339040) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@370598a; line: 1, column: 416]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbCA', u'error': {u'caused_by': {u'reason': u'Numeric value (125038218515) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@69222c3c; line: 1, column: 369]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}, {u'index': {u'status': 400, u'_type': u'file', u'_id': u'AVuwLl5Dj6xDPJklVbCB', u'error': {u'caused_by': {u'reason': u'Numeric value (125038218516) out of range of int\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@42983f0b; line: 1, column: 381]', u'type': u'json_parse_exception'}, u'reason': u'failed to parse [inode]', u'type': u'mapper_parsing_exception'}, u'_index': u'diskover-2017.04.22'}}])`

**Comment by shirosaidev** [comment]
This was an issue with inode mapping in the Elasticsearch index that was being created at runtime. It was set to type int which is not big enough to hold the value. I've changed it to long. Please update to version 1.0.2 which should fix this.

**Comment by CopyRunStart** [comment]
The latest update fixed it, thank you.  This will be great for my production team to be able to see visually where and what their data is.  

Also worth mentioning, maybe something you can add to your guide for people who are new to Kibana like me.  Nothing was showing in the dashboard until I went to: Management > Index Patterns diskover-* > and then hit the refresh icon.

**Comment by shirosaidev** [comment]
Happy to hear it's working good for you now. Will add your Kibana tip to the readme. Which studio are you at? If you are on SSA slack chat, private message me to say hi.
