### ISSUE TITLE
Inaccurate results and missing files using workers

### ISSUE THREAD

**Issue by Azenet** [shirosaidev/diskover#21]
Hi,

I used diskover previously when it was only a single process crawling, I updated to master (038a1cdfaf336e4aa9fe782a722bdea90d2255a5) and I now find results to be extremely inaccurate, many files are missing. My home folder is reported to be 75GB when it is 3.5TB large, a folder inside that is reported to weight 230GB and containing 2600 files when it is actually 2TB large containing 70k files.
In the web UI, folders that miss files are listed containing 1 item, and when clicked diskover reports no items found (query becomes `path_parent:\/...\/path`).
Is this a known issue with the current crawling bot scheme?

Command line used: `python diskover.py -d /home/ -i diskover-12042018 -a`
Run log:
```
2018-04-12 13:34:14,943 [INFO][diskover] Checking es index: diskover-12042018
2018-04-12 13:34:14,946 [WARNING][diskover] es index exists, deleting
2018-04-12 13:34:15,583 [INFO][diskover] Creating es index
2018-04-12 13:34:16,449 [INFO][diskover] Adding disk space info to es index
2018-04-12 13:34:16,619 [INFO][diskover] Found 8 diskover RQ worker bots
2018-04-12 13:34:16,619 [INFO][diskover] Enqueueing crawl to diskover worker bots for /home...
2018-04-12 13:34:16,619 [INFO][diskover] Sending adaptive batches to worker bots
Crawling: [=====] 100% (Elapsed Time: 1:33:27, Time:  1:33:27)
2018-04-12 15:07:43,832 [INFO][diskover] Finished crawling!
2018-04-12 15:07:43,832 [INFO][diskover] Waiting for diskover bots to be done with any crawl jobs...
2018-04-12 15:11:48,650 [INFO][diskover] Getting diskover bots to calculate directory sizes...
2018-04-12 15:11:48,650 [INFO][diskover] Searching for all directory docs in diskover-12042018
2018-04-12 15:13:19,920 [INFO][diskover] Found 707085 directory docs
2018-04-12 15:13:30,117 [INFO][diskover] Directories have all been enqueued, calculating in background
2018-04-12 15:13:30,367 [INFO][diskover] Dispatcher is DONE! Sayonara!
```

Thank you!

**Comment by shirosaidev** [comment]
Can you try to update to rc1 release and then run diskover using root (sudo), including bots. Are all the directories/files you are indexing owned by your user?

**Comment by Azenet** [comment]
I updated to rc1 and ran a new scan with 8 workers (same count as before). Results seems to be slightly better but the issue is still there. I forgot to mention it but I was running diskover as root already.

**Comment by shirosaidev** [comment]
are you running the workers as root as well? Are there any failed jobs in the rq (redis queue) after crawl finishes? Are you waiting for all directory calculation processes to finish in background before looking in diskover-web?

**Comment by Azenet** [comment]
Yes, everything runs as root. I'm not sure about the redis queue, I ran `redis-cli keys * | wc -l` which yields 713799, and diskover-web says it found 707085 directories (I'm only assuming the two are related). The workers seems to idle (no CPU time and no new files are discovered in diskover-web).

**Comment by shirosaidev** [comment]
install rq-dashboard http://python-rq.org/docs/monitoring/ and then see if there are any failed frames (failed queue) and let me know the errors in the failed frames.

**Comment by shirosaidev** [comment]
are you running diskover-web v1.5.0-rc1 ? If not please update to that version as well.

**Comment by Azenet** [comment]
Yes, I am running web with v1.5.0-rc1 as well. I checked rq-dashboard, there are many failed jobs and the error seems clear:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/diskover/diskover_worker_bot.py", line 494, in scrape_tree_meta
    es_bulk_adder(tree, cliargs, bot_logger)
  File "/opt/diskover/diskover_worker_bot.py", line 464, in es_bulk_adder
    diskover.index_bulk_add(es, filelist, 'file', diskover.config, cliargs)
  File "/opt/diskover/diskover.py", line 563, in index_bulk_add
    request_timeout=config['es_timeout'])
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 95, in _process_bulk_chunk
    resp = client.bulk('\n'.join(bulk_actions) + '\n', **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 292: ordinal not in range(128)
```

I'm using Elasticsearch 5.6.2 and the python client is elasticsearch 5.5.2, which seems to be the latest available for Elasticsearch 5.x.

**Comment by shirosaidev** [comment]
those error message line numbers don't seem to correspond with the latest version of diskover v1.5.0 rc1. Can you verify your md5 sum of these files are the same?
MD5 (diskover.py) = 5ca30bf29356adf0efbf7b56c2f0f024
MD5 (diskover_worker_bot.py) = c6d75e5ca815d59e35efc1ca06a0f58c

What is output when you run python diskover.py -V ?

**Comment by shirosaidev** [comment]
maybe those error messages were from previous version of diskover though, maybe try clearing the failed jobs and run again if the md5 sums match.

**Comment by Azenet** [comment]
Sorry, the trace I included was indeed from the previous checkout of master (038a1cdfaf336e4aa9fe782a722bdea90d2255a5) I was using. Here is a stack trace I got from my earlier run that comes from diskover v1.5.0-rc1:
```
Traceback (most recent call last):
  File \"/usr/local/lib/python2.7/dist-packages/rq/worker.py\", line 789, in perform_job
    rv = job.perform()
  File \"/usr/local/lib/python2.7/dist-packages/rq/job.py\", line 573, in perform
    self._result = self._execute()
  File \"/usr/local/lib/python2.7/dist-packages/rq/job.py\", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File \"/opt/diskover/diskover_worker_bot.py\", line 534, in scrape_tree_meta
    es_bulk_adder(tree, cliargs, bot_logger)
  File \"/opt/diskover/diskover_worker_bot.py\", line 477, in es_bulk_adder
    diskover.index_bulk_add(es, filelist, 'file', diskover.config, cliargs)
  File \"/opt/diskover/diskover.py\", line 569, in index_bulk_add
    request_timeout=config['es_timeout'])
  File \"/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py\", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File \"/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py\", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File \"/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py\", line 95, in _process_bulk_chunk
    resp = client.bulk('\\n'.join(bulk_actions) + '\\n', **kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 309: ordinal not in range(128)
```

------

I am in an environment in which I only have python 3.5.3 and not 3.6.4 at the moment, trying with this version yields this error in rq while scanning for folders (not the background task yet):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 789, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 573, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 579, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/opt/diskover/diskover_worker_bot.py", line 513, in scrape_tree_meta
    dmeta = get_dir_meta(root, cliargs, reindex_dict)
  File "/opt/diskover/diskover_worker_bot.py", line 219, in get_dir_meta
    redis_conn.set(path, mtime_unix + ctime_unix, ex=diskover.config['redis_dirtimesttl'])
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 1171, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 650, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 119, in encode
    value = value.encode(self.encoding, self.encoding_errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce9' in position 64: surrogates not allowed
```

**Comment by shirosaidev** [comment]
Looks like there are some directories/files with special characters causing these unicode errors. I'll look at catching this unicode error and handling it in the next release. For now, can you see which files/directories are causing this to help me to write the fix? Thanks
find /home | perl -ne 'print if /[^[:ascii:]]/'

**Comment by shirosaidev** [comment]
Please try this latest patched version (diskover_worker_bot.py) and let me know if it fixes this issue.

**Comment by Azenet** [comment]
This is unfortunately too broad, I have lots of files with non-ascii characters. The python 3.5 run seems to be done and workers are idling, there are 2 errors and they have the same redis-related stack trace. The characters that are not handled properly in both errors are `\udce9`, which seems to be an invalid character. This is in older files, the characters seems to have replaced `é` accents in some file names. However, it seems that except for the directories that could not be handled, running diskover with python 3 caught all the files! So this was definitely a python2 unicode issue.

**Comment by carlchan** [comment]
Still seems to happen with rc10.  Consecutive runs of
`python3.6 diskover.py -A -a -d /mnt`
report different "Found XXXX directory docs" each time.

No failed jobs in RQ-dashboard nor on console.

If I try the same in python2.7, I get this on the console:
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 73: invalid continuation byte

and in rq-dashboard, the diskover_worker_bot.scrape_tree_meta task fails with
> Work-horse process was terminated unexpectedly (waitpid returned 256)

**Comment by shirosaidev** [comment]
are you running the worker bots with the same version of Python as diskover.py?

**Comment by shirosaidev** [comment]
I just pushed some updates to rc10, please update and let me know if you are still seeing large diff dir/file counts after crawl finishes after a couple new runs.

**Comment by carlchan** [comment]
@shirosaidev yes, I stop all existing bots and restart them using the same python version.  I made sure all tasks were completed and nothing was left in the queues in rq-dashboard as well before each run.

Will try latest patches soon.

**Comment by carlchan** [comment]
Still pretty inconsistent.  Not sure how to help track this down?

**Comment by shirosaidev** [comment]
this is a bug i'm working on in rc10, its related to switching to multiprocessing for tree walking, previously was using threading. I've pushed some updates just now, please test it out and let me know.

**Comment by shirosaidev** [comment]
closing this issue, please open a new one if you are still having this issue with latest rc10.

**Comment by carlchan** [comment]
Just finished a run with the latest pull, it's slower than it used to be but that's a good thing, I think it's now crawling properly, thank you.
Will be running another test on a bigger pool shortly and will let you know if I find issues.

**Comment by shirosaidev** [comment]
@carlchan thanks for the feedback. You can adjust the number of tree crawling procs in diskover.cfg (copy from .sample if you don't have it) to the amount of cpu cores you have x2 might be a good start for the crawl. The tree procs are used to parallel each subdir in rootdir (level 1 only).
