### ISSUE TITLE
diskover.py error when running indexing commands

### ISSUE THREAD

**Issue by hyattdrew11** [shirosaidev/diskover#24]
Traceback (most recent call last):
  File "diskover.py", line 1464, in <module>
    config = load_config()
  File "diskover.py", line 175, in load_config
    t = config.get('autotag', 'files')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'autotag'

**Comment by shirosaidev** [comment]
update to the latest rc10 i just pushed and copy autotag section (and any others missing) from diskover.cfg.sample to your diskover.cfg and adjust for your environment.

**Comment by shirosaidev** [comment]
@hyattdrew11 did you get it working now copying over config settings from diskover.cfg.sample?

**Comment by hyattdrew11** [comment]
Yeah thanks for the quick reply.

**Comment by shirosaidev** [comment]
there has been a lot of changes/updates to rc10, hoping to finalize it soon, try to grab the latest off github.
