### ISSUE TITLE
Auto-tag behaviour

### ISSUE THREAD

**Issue by carlchan** [shirosaidev/diskover#25]
Been trying the autotag feature, but getting poor results.

Config looks like this:
```
files =
  [ {"name": [], "name_exclude": [],
     "ext": ["tmp*", "TMP*", "temp*", "TEMP*", "cache*", "CACHE*"],
     "path": [],
     "path_exclude": [], "mtime": 90, "atime": 0, "ctime": 90,
     "tag": "delete", "tag_custom": "autotag"},

  { "name":[], "name_exclude": [],
    "ext": ["zip", "ZIP", "dmg", "DMG", "iso", "ISO", "gz", "bz2"],
    "path": [], "path_exclude": [],
    "mtime": 0, "atime":0, "ctime":0,
    "tag": "archive", "tag_custom": "archive" },

  { "name":[], "name_exclude": [],
    "ext": ["mov","MOV","mp4","MP4","m4v","M4V","avi","AVI"],
    "path": [], "path_exclude": [],
    "mtime": 0, "atime":0, "ctime":0,
    "tag": "keep", "tag_custom": "video" },

  { "name":["DSCF*","dscf*","IMG_*","img_*"], "name_exclude": [],
    "ext": ["cr2","CR2","RAF","raf"],
    "path": [], "path_exclude": [],
    "mtime": 0, "atime":0, "ctime":0,
    "tag": "keep", "tag_custom": "rawimage" }
  ]
```

However, the only thing that gets tagged correctly is DSCF*.RAF
None of the other files specified in the search seem to be working, all are still untagged.

Am I doing something wrong?

**Comment by shirosaidev** [comment]
I pushed a few patches just now for rc10, please update and let me know if the auto tags work for you now. If not, please reply with some example filenames that work and some that don't.

**Comment by carlchan** [comment]
Thanks for the quick response.
That's now tagging everything defined in the "keep/rawimage" section, but none of the other definitions are tagging.

I think it's not handling undefined names/ext search correctly.  For example, looking at 
```
            try:
                for ext in pattern['ext']:
                    if ext.startswith('*') and ext.endswith('*'):
                        ext = ext.replace('*', '')
                        if re.search(ext, metadict['extension']):
                            extpass = True
                            break
                        else:
                            extpass = False
                    elif ext.startswith('*'):
                        ext = ext + '$'
                        if re.search(ext, metadict['extension']):
                            extpass = True
                            break
                        else:
                            extpass = False
                    elif ext.endswith('*'):
                        ext = '^' + ext
                        if re.search(ext, metadict['extension']):
                            extpass = True
                            break
                        else:
                            extpass = False
                    else:
                        if ext == metadict['extension']:
                            extpass = True
                            break
                        else:
                            extpass = False
            except KeyError:
                pass
```
If ext is undefined, then it goes to exact match instead of wildcard.  Conversely, if you use "*" then it'll go to "starts and ends with *", but replaces the "*" with '' which also will never match.

May either have to have a special case for * or '', or maybe just allow plain regex directly since that's what the search uses anyway.....?

**Comment by carlchan** [comment]
Never mind I'm off the mark there, sorry.
It seems to work with just the LAST pattern definition, I wonder if previous matches in the "for pattern in" loop is getting overwritten?

**Comment by carlchan** [comment]
Ah yes, it is getting overwritten.

**Comment by carlchan** [comment]
Created a pull request for the fix, not sure how to link it to this issue.

**Comment by shirosaidev** [comment]
thank you for that patch, I've merged it into master branch.

**Comment by carlchan** [comment]
glad to help!
