### ISSUE TITLE
Docker Support?

### ISSUE THREAD

**Issue by victorhooi** [shirosaidev/diskover#28]
I saw that diskover-web recently merged in docker support =):

https://github.com/shirosaidev/diskover-web/pull/8/files

That is awesome!

Does it make sense to also have a Docker instance for Diskover itself?

(Use-case - I want to run this on FreeNAS, within a Docker instance)

**Comment by shirosaidev** [comment]
I am working with the guys over at linuxserver.io on getting diskover into their docker images. If you want to help out with the testing, head over to linuxserver.io discord and direct message @hackerman who is helping with the docker build.

**Comment by shirosaidev** [comment]
official linuxserver.io image has been released:
https://hub.docker.com/r/linuxserver/diskover/
