### ISSUE TITLE
Directory with a trailing space kills crawl

### ISSUE THREAD

**Issue by ronaldknol** [shirosaidev/diskover#3]
Since our storage is accessed from Mac we are seeing a lot of entries (files and directories) with a trailing space in the name (because artists make a new folder and paste a copied string which contains a trailing space).
This is normally no issue for any tool (makes it tricky in the terminal) but kills the crawl:

```
[2017-04-27 13:05:13] [status] Finding directories to crawl
Crawling: [66%] |██████████████████████████--------------| 176/268Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ronald/diskover/diskover.py", line 251, in processDirectoryWorker
    filelist = crawlFiles(path, DATEEPOCH, DAYS, MINSIZE, EXCLUDED_FILES, VERBOSE)
  File "/home/ronald/diskover/diskover.py", line 158, in crawlFiles
    for name in os.listdir(path):
OSError: [Errno 2] No such file or directory: './.cleanup/2016_F4_JUNE_WORK STYLES'
```
This folder is actually `.cleanup/2016_F4_JUNE_WORK STYLES /`

I removed `name = name.strip()` from line 159 in diskover.py but still get an exception.
I'm pretty sure it's the `find -type d` command that doesn't properly show the trailing space.
I would be curious to see how `find` deals with unicode characters and the rest of the os library.

**Comment by shirosaidev** [comment]
I've changed some code for newline character removal for directories and filenames and tested your directory name with the trailing space. Please update to **version 1.0.3** which should fix this bug now.

**Comment by ronaldknol** [comment]
Indeed, 1.0.3 fixes the issue.
I've also tested a directory with a unicode character, that gets parsed properly too.

**Comment by shirosaidev** [comment]
Thanks Ronald for testing and happy to hear it's working now for you. If you are on SSA slack chat, private message me and let me know which studio you are at. Always curious where Diskover will end up getting used.

**Comment by varontron** [comment]
For anyone else who arrives here:  a related issue that is not a caused by a diskover bug is caused by some `mount.cifs` implementations on linux and Mac OS X, when crawling mounted volumes, resulting in I/O errors that effectively kill the crawl.  Specifying `mapchars` in the 'mount.cifs' config solved this problem for me.  Credit to https://valentijn.sessink.nl/?p=652 with explanation and links to docs.
