### ISSUE TITLE
 Discrepancies between file system and diskover-web reporting 

### ISSUE THREAD

**Issue by BuildMonkey** [shirosaidev/diskover#36]
I am currently evaluating diskover and there are some differences between what diskover-web is reporting and what is on the file system.

* The file system that the crawlers are indexing is 485TB; however, the index information on the dashboard-web shows Total 800TB, Used 484.65TB, Free 315.35TB, and Available 315.35 TB. It also shows in the Jumbotron that 'You could save 1.39 PB of disk space if you delete...'.
* I ran a report and evaluated the results from a single subdirectory. The results shows duplicate listing of files where the directory only contains a single copy.
* du is reporting the directory is 154M while diskover-web is reporting 78.01M.

I am sure you will need more information to better understand what is going on, so I hope this helps start the dialogue. Please let me know what additional information you need, or person provide some inside into why we are seeing results that to us, seem incorrect.

Thanks.

**Comment by shirosaidev** [comment]
please update to latest rc21 as that version has been going through a lot of patches/updates recently. Can you send the full commands you are running?

**Comment by shirosaidev** [comment]
are you referring to the disk space overview in the top right side of dashboard? Could you send screenshot and also the output of `df -h /rootdir` of same as you used -d rootdir.

**Comment by BuildMonkey** [comment]
<img width="425" alt="screen shot 2018-11-12 at 4 23 15 pm" src="https://user-images.githubusercontent.com/26270838/48329195-7c05b880-e697-11e8-9212-725348d1886c.png">

$ df -h /mnt/DIRECTORY
Filesystem                                Size  Used Avail Use% Mounted on
//physical.loc/DIRECTORY$  800T  485T  316T  61% /mnt/DIRECTORY

The crawlers command used:
$ python diskover_worker_bot.py &

The command used was to manage the crawlers:
$ python diskover.py -i diskover-test -d /mnt/DIRECTORY -a -O -n 

For obvious reasons, I am unable to provide you the actual name of the directory, but I believe the information is there that you need. Please let me know if you need additional information. 

In the meantime, I will update to rc21 per your suggestion.

**Comment by BuildMonkey** [comment]
I just updated the crawler to rc22 and received the following error in the log when I ran the crawlers.

  d8-3f3c-44c0-8842-02bf4582eff7)
02:07:14 AttributeError: 'module' object has no attribute 'scrape_tree_meta'

02:07:14 Moving job to u'failed' queue
 
Is there a way we can rectify?

**Comment by BuildMonkey** [comment]
I also noticed that the -n option is no longer available for the diskover.py script. As a result, when the script is restarted, it deletes the previous run of the index and starts again. Because we are working on a large disk space, we would like to keep the previous data collected, rather than the crawlers starting over again. Is there a reason why this option was removed?

2018-11-12 16:42:21,075 [INFO][diskover] Checking es index: diskover-TEST
2018-11-12 16:42:21,077 [WARNING][diskover] es index exists, deleting
2018-11-12 16:42:21,171 [INFO][diskover] Creating es index

**Comment by shirosaidev** [comment]
> <img alt="screen shot 2018-11-12 at 4 23 15 pm" width="425" src="https://user-images.githubusercontent.com/26270838/48329195-7c05b880-e697-11e8-9212-725348d1886c.png">
> 
> $ df -h /mnt/DIRECTORY
> Filesystem Size Used Avail Use% Mounted on
> //physical.loc/DIRECTORY$ 800T 485T 316T 61% /mnt/DIRECTORY
> 
> The crawlers command used:
> $ python diskover_worker_bot.py &
> 
> The command used was to manage the crawlers:
> $ python diskover.py -i diskover-test -d /mnt/DIRECTORY -a -O -n
> 
> For obvious reasons, I am unable to provide you the actual name of the directory, but I believe the information is there that you need. Please let me know if you need additional information.
> 
> In the meantime, I will update to rc21 per your suggestion.

the chart in diskover-web seems to match the output of df...

**Comment by shirosaidev** [comment]
for new crawls, you can change the index name with -i <indexname> to a new name so the previous index does not get overwritten and a new index gets created.

**Comment by shirosaidev** [comment]
please see the readme for using reindex flags for adding additional directories to an existing index.

**Comment by BuildMonkey** [comment]
The jumbotron output said that we could save 1.2PB even though the dashboard was showing the right output in the upper left hand corner.
"You could save 1.2 PB of disk space if you delete..."
Why would that message be so far off?

I don't want to use new crawls, but I want to make sure that the original has completed. We are seeing on the screen that the "Worker bots still running! Some analytics pages will not load until worker bots have finished..."
We want to ensure the index run has completed and evaluate the results. How can we ensure this has happened while still using the same index?

**Comment by BuildMonkey** [comment]
I am seeing discrepancies with the results, and I cannot tell if it is due to the feedback I provided in my last comment, where the dashboard states that the worker bots are still running.

For example, on the filesystem, I see 202661 .mov files while the index is returning 88572. I believe I have set the hardlinks at the right value to account for this. Do you have any suggestions why these numbers are not the same?

**Comment by shirosaidev** [comment]
You can use rq-dashboard to see the stats of workers and jobs. Also the output of diskover.py will show if the crawl is still running. If jumbotron is showing a large file size, it is most likely from a large amount of hardlinks. When the crawl is running, updates to the es index only happen every 30 sec (refresh time in diskover.cfg) to help improve indexing time.

**Comment by BuildMonkey** [comment]
I am lumping a lot of elements together in this comment, so I will try to break apart into sections to make it easier to understand.

** Determine crawlers, diskover.py, has completed**
Per your suggestion, I looked to see if the crawlers completed. I see that the the crawlers are still in the background as a unix process. When looking at the status, /proc/$PID/status, it looks like they are sleeping, so it seems like the script is done with the index is was given. However, the orange banner stating the crawlers are not done is still showing. This is what has us puzzled. Are there ways for us to determine this is a red herring, or from our side, ensure it appears in correct circumstances?

I don't believe it is feasible to monitor the stdout for the python crawlers script, since our test directory takes over 8 hours, and people accidentally close terminal or restart their machines. I guess we can have the output go to a log. Do the crawlers currently write to a log?

** Adding to index**
You suggested the following to add more directories to an index "please see the readme for using reindex flags for adding additional directories to an existing index." This suggestion doesn't necessarily pertain to our concerns. If a crawler does not appear to be done or seems to have died unexpectedly, we would like to restart from the top of the index, since we are unsure if all the files were recorded from the previous index run. Is this possible?

**Hardlinks**
Yes, we certainly do have a lot of hardlinks. I notice there is an info point below the jumbotron: "Does not account for hardlinks." Can you please explain what this means? For example, does this mean that diskover treats hardlink files as a unique file when providing the overall index disk size? 

I can see in the 'Advance Search' that you can search for files with hardlinks, but we were wondering if you can search for all hardlinks for a particular file. So if a hardlink is contained in another directory with another filename, would the advance search be able to perform this search?

Thank you for taking the time to address these answers. It will help us effectively use diskover.

**Comment by shirosaidev** [comment]
Worker bots run indefinitely unless using -b --burst flag. They wait for rq jobs in redis and process those directory batches then bulk add the meta stat results into ES. If the banner in diskover-web is showing that means there was some sort of error in the crawl or the bots are not done processing all jobs in rq, using rq and rq-dashboard can help with seeing this.
There is no way currently to continue an index where it left off if there is some type of error. You have to start over and overwrite the index.
Hardlink files are treated as separate es doc and are accounted to the directory sizes when running dir calcs at end of crawl.
You can search for all file hardlinks using inode number of a file.

**Comment by shirosaidev** [comment]
Please update to latest rc23, restart all the bots, and let me know if you have any other issues.
