### ISSUE TITLE
Redis version not being detected correctly

### ISSUE THREAD

**Issue by OFark** [shirosaidev/diskover#41]
So everything has been running just fine in my unRAID env with Redis, ElasticSearch and Diskover. However I had a flurry of updates last week, I know Redis was updated, not sure about Diskover. However now Diskover doesn't detect the right version of Redis. At least that's what it looks like to me:

> pkg_resources.ContextualVersionConflict: (redis 2.10.6 (/usr/lib/python3.6/site-packages), Requirement.parse('redis>=3.0.0'), {'rq'})

Full Log:
[https://pastebin.com/KVUU5tjW](https://pastebin.com/KVUU5tjW)

However my REDIS is version 4.0.9:
[https://imgur.com/eNHE5vL](https://imgur.com/eNHE5vL)

**Comment by OFark** [comment]
Well, I checked it again today and it was still throwing errors. So I removed and readded it, working fine now. Thanks for the update.

**Comment by OFark** [comment]
Spoke too soon, the webpage is now working but the logs still showing the error and the crawl never runs.

**Comment by OFark** [comment]
Log output looks the same, I haven't rolled back to rc24, from your previous message I thought you said they'd released an update that fixed it. That'd be why it still doesn't work. I can't get pip to work, inside the diskover container pip is an unrecognised command.

**Comment by OFark** [comment]
v1.5.0-rc24-ls8 is working so far.

**Comment by shirosaidev** [comment]
yes, I think since rc24-ls9 it was built when requirements.txt did not have set version numbers and the new builds pulled down new versions of rq and redis (python) and causes diskover not to work. ls8 was built before there were the new versions of rq and redis that don't work with diskover. This Friday when rc25 latest gets built it should work.

**Comment by shirosaidev** [comment]
It looks like there is a new built v1.5.0-rc25-ls10 image on docker hub. Please try it out and reply back if working okay. Thank you.

**Comment by OFark** [comment]
Ahh yeah, I left this response on the unRAID forum too:

The REDIS version issues has been fixed by that version, but there's a new one:
starting crawler with following options: --finddupes -i diskover-
Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 1138, in _unify_values
    sectiondict = self._sections[section]
KeyError: 'ownersgroups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./diskover.py", line 1851, in <module>
    config, configfile = load_config()
  File "./diskover.py", line 172, in load_config
    configsettings['ownersgroups_uidgidonly'] = config.get('ownersgroups', 'uidgidonly').lower()
  File "/usr/lib/python3.6/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.6/configparser.py", line 1141, in _unify_values
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'ownersgroups'

I tried removing and reinstalling Diskover, deleting the appdata dir and pointing the /data dir at several different locations that have worked before. Still the same issue.

**Comment by shirosaidev** [comment]
copy over any missing sections from diskover.cfg.sample to diskover.cfg

**Comment by OFark** [comment]
it appears diskover_connections.py os looking for a load of config options that are never specified. redis_retry_on_timeout, redis_socket_keepalive for starters

**Comment by shirosaidev** [comment]
try to bash into the container and run
`python3 diskover_worker_bot.py`

**Comment by shirosaidev** [comment]
Try v1.5.0-rc27-ls13 when released later today or tomorrow and let me know if all working good. I pushed a pr into the lsio container to update the default cfg with the container and @hackerman accepted it so that will be in the new lsio container builds now on docker hub.

**Comment by shirosaidev** [comment]
v1.5.0-rc28 should be released in the next few days which should fix this

**Comment by shirosaidev** [comment]
message me on linuxserver.io discord @shirosai

**Comment by OFark** [comment]
Well, I'm no longer getting any errors in the log files, however, I don't seem to be seeing any updates. I'm not sure if the cron isn't running or if the crawl isn't working I haven't had time to investigate.
