### ISSUE TITLE
Directories containing a large number of files never complete

### ISSUE THREAD

**Issue by seanbales** [shirosaidev/diskover#43]
Directories that contain a large number of files, in our case it was nearly 200,000 files, would never complete.  After debugging I found that the scandirwalk_worker function has a minor bug.  It is possible for the q_paths queue to be empty and the q_paths_results queue to also be empty while one or more scandirwalk_worker threads are still working because the directories take so long to get through.  The scandirwalk function will erroneously exit if both queues are empty and mistakenly end the program before it is finished.  There needs to be some mechanism to track jobs that are in-progress, being processed by the scandirwalk_worker function.  I will submit a merge request with a patch that fixed this for me.

**Comment by shirosaidev** [comment]
merged pr into latest rc25, thanks for this patch.
