### ISSUE TITLE
io exception warning should be logged to a log file

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#45]
if diskover runs as a background task it would be good if it logs warnings and errors to a selectable log file

**Comment by shirosaidev** [comment]
what about just shell redirecting to a log file when running in background?

python diskover.py ... >> /var/log/diskover.log 2>&1 &

**Comment by shirosaidev** [comment]
bots can log using BOTLOG variable in diskover-bot-launcher.sh, just set that to a file, by default it is blank BOTLOG= which causes logs to go to /dev/null.

**Comment by mathse** [comment]
I tried that ... but the only thing which gets log is the header of the bot ;-( no IO Errors or Warnings

   ___  _ ____ _  _ ____ _  _ ____ ____     ;
     |__> | ==== |-:_ [__]  \/  |=== |--<    ["]
     ____ ____ ____ _  _ _    ___  ____ ___ /[_]\
     |___ |--< |--| |/\| |___ |==] [__]  |   ] [ v1.5.0-rc26

     Redis RQ worker bot for diskover crawle

**Comment by shirosaidev** [comment]
I just tested this with python 3.6.5 setting BOTLOG=./workerbot.log in diskover-bot-launcher.sh. I started 1 bot using bot launcher and all log output for the bot goes to ./workerbot.log.1.
Check LOGLEVEL=2 in diskover-bot-launcher.sh near the top of the file.

**Comment by shirosaidev** [comment]
In upcoming rc27 errors for any io/os errors from getting file meta will be printed out in bots.

**Comment by shirosaidev** [comment]
check if you have the latest version of diskover-bot-launcher.sh (same as what's on github) and then open the file and edit the top settings for your env.
