### ISSUE TITLE
Inodes too big for Elastic

### ISSUE THREAD

**Issue by seanbales** [shirosaidev/diskover#49]
It looks like Diskover uses data type "Float" for inodes but inodes in Isilon can be much larger than the Float data type will consider as significant digits.  It looks like a "Float" in Elastic is an IEEE 754 number which appears to have a maximum value of 3X10^38 but only 22 digits are explicitly stored making any inode larger than 4194304 lose precision and because Isilon can support Inodes in the hundreds of billions the inodes stored end up being incorrect if they are larger than 2^22.

We found this because when we try to search for inodes (using diskover-web or Kibana), we get results for files that do not actually match the inode we searched for because it is only searching for the first 7 significant digits.

The data type for Inode should be set to "double" or "long" in order to fix this issue.  Without this change, any inode larger than 4194304 could be stored wrong in Elastic and will never be accurately searchable.

**Comment by shirosaidev** [comment]
this has been changed in latest rc27 code, switched to keyword for inode field mapping
