### ISSUE TITLE
leftover DEBUG in diskover.py:365

### ISSUE THREAD

**Issue by ronaldknol** [shirosaidev/diskover#5]

**Comment by ronaldknol** [comment]
There's a leftover use of DEBUG in indexAdd() but you're no longer passing DEBUG to the function.
This causes a fatal exception when that code is triggered.

**Comment by shirosaidev** [comment]
I released version **1.0.4** tonight which should fix this issue. Please update and reply if it's fixed.

**Comment by shirosaidev** [comment]
I've removed the debug code from Diskover, will close this issue.
