### ISSUE TITLE
diskover_dupes seams to have memory problems

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#51]
I tested rc29 but it looks like it has memory problems

specs: 72 cores, 92gb ram, 8gb for elasticsearch
as soon as diskover is searching for dupes (4000 in my test) it soonish prints out "cannot allocate memory"

rc28 works fine though

**Comment by shirosaidev** [comment]
please try pulling the latest rc29 code, I've changed this now from default cpu cores x 2 to 8 threads (adjustable in diskover.cfg), copy new settings from diskover.cfg.sample **dupescheck** section
