### ISSUE TITLE
autotag for dirs only tags the first definition

### ISSUE THREAD

**Issue by mathse** [shirosaidev/diskover#55]
i created the following autotag definition

```dirs = [{"name":["*tmp*","*TMP*","*temp*","*TEMP*","*Temp*","*cache*","*CACHE*","*Cache*","*to*delete*"],"name_exclude":["*emperatur*","*emplate*"],"path":[],"path_exclude":[],"mtime":90,"atime":0,"ctime":90,"tag":"delete","tag_custom":"autotag"},{"name":["*FORMER*LAB*MEMBERS*"],"name_exclude":[],"path":[],"path_exclude":[],"mtime":0,"atime":0,"ctime":0,"tag":"archive","tag_custom":"autotag"}] ```

but the autotagger only tags the first definition

**Comment by shirosaidev** [comment]
are the directories named *FORMER*LAB*MEMBERS* have mtime and ctime 90+ days? If so, that is why the autotag is tagging those with delete/autotag tags. It stops going through the list once it reaches a match.

**Comment by shirosaidev** [comment]
So directories with `*FORMER*LAB*MEMBERS*` in their names are not getting tagged at all?

**Comment by shirosaidev** [comment]
can you reply with an example full path directory that is not getting tagged? Are you restarting the bots after editing the diskover.cfg tags ?

**Comment by mathse** [comment]
ahhhh...
the folder is called 'FORMER LABMEMBERS'
no wonder its not getting tagged
