### ISSUE TITLE
When running crawlbot, getting NameError: name 'cliargs' is not defined

### ISSUE THREAD

**Issue by LEMNX** [shirosaidev/diskover#63]
```
/ Crawling (Queue: 0) Elapsed Time: 0:00:00                                                                                          2019-06-19 16:21:16,670 [INFO][diskover] Starting crawl using 16 treewalk threads (maxdepth 1)

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/opt/diskover/diskover.py", line 1524, in scandirwalk_worker
    if cliargs['debug'] or cliargs['verbose']:
NameError: name 'cliargs' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/diskover/diskover.py", line 1549, in scandirwalk_worker
    logger.error("[thread-%s] Exception caused by: %s" % (threadn, e))
NameError: name 'logger' is not defined
```

I have logger and cliargs installed on the system, not sure why of the error. This is with v1.5.0-rc30

**Comment by shirosaidev** [comment]
I pushed some updates to v1.5.0-rc30 which fixes running --crawlbot mode.

**Comment by LEMNX** [comment]
Thanks @shirosaidev, It helped when I read the changelog and code.
The script need to check for missing dependant crawlapi_url cli options then crash out if they are not passed. Also the https://github.com/shirosaidev/diskover/wiki/Crawl-bot-(continuous-scanning) needs to say you need to setup diskover-web.

Happy to do a PR

**Comment by shirosaidev** [comment]
diskover-web is not needed for crawlbot mode, it's just a frontend ui for diskover index searching, fs analytics, etc.

**Comment by shirosaidev** [comment]
i've pushed some updates which should fix any issues around crawlapi. If you don't want to use the crawlapi, don't run with --crawlapi and comment out that section in diskover.cfg (see diskover.cfg.sample).

**Comment by shirosaidev** [comment]
@LEMNX is everything working now as expected when running with --crawlbot ?
