### ISSUE TITLE
 Exception caused by: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by jimezdoesit** [shirosaidev/diskover#66]
While running a crawl, getting several of these errors and the Queue never seems to advance. 
=============================================
/ Crawling (Queue: 86, 196.607 dirs/sec) Elapsed Time: 0:09:23                                                         2019-07-07 15:29:45,381 [ERROR][diskover] [thread-2] Exception caused by: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "diskover.py", line 1538, in scandirwalk_worker
    for entry in scandir(path):
  File "/usr/lib64/python3.6/site-packages/scandir.py", line 576, in scandir_python
    name = name.decode(file_system_encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byte

**Comment by shirosaidev** [comment]
can you try running in verbose mode --verbose with diskover.py and see which file path is causing this error?

**Comment by shirosaidev** [comment]
I've put in a check for this error in v1.5.0.4 which will now print a warning with path instead of raising an error
