### ISSUE TITLE
Index without dash causes exception

### ISSUE THREAD

**Issue by ronaldknol** [shirosaidev/diskover#7]
Running diskover with `-i <indexname>` where the index name does not have a dash (-) causes an exception:

```
user$ diskover.py -i diskover.mnt.20170505 -d /mnt
[2017-05-05 07:41:52] [status] Connecting to Elasticsearch
<snipped output>
[2017-05-05 08:06:53] [status] Finished crawling
Traceback (most recent call last):
  File "diskover.py", line 517, in <module>
    main()
  File "diskover.py", line 495, in main
    INDEXSUFFIX = INDEXNAME.split('diskover-')[1].strip()
IndexError: list index out of range
```

Maybe put a check at the top of the code to see if the index name contains (starts with) `diskover-` and fail with a verbose message, rather than running through all the code and filesystem and fail at the end?

**Comment by shirosaidev** [comment]
I've added a check in **version 1.0.6** that the index is named diskover-<string> which fixes this.
