### ISSUE TITLE
Hi I DESPERATELY need help, please, total newbie, i will pay you. i just wanna get this damn thing up and running

### ISSUE THREAD

**Issue by alih1029** [shirosaidev/diskover#73]
ripping my hair out at this point.
i have zero programming knowledge, can you help me?
I've installed gitdesk and downloaded your program and have no idea what to do now?

**Comment by shirosaidev** [comment]
There is a newly written Linux installation guide here https://github.com/shirosaidev/diskover/wiki/Installation-Guide
If you are still struggling, you can get a diskover vmware ova's if you want to become a Patron on Patreon or linuxserver.io has built docker hub images for diskover if you want to use docker. You can join the diskover Slack workspace and get help there as well.

**Comment by dbine** [comment]
alih1029, are you still looking for help? Happy to get this running for you for some compensation.  Hit me with your thoughts.  Thanks~
