### ISSUE TITLE
Ideographic space breaks folder size calculation

### ISSUE THREAD

**Issue by Suika** [shirosaidev/diskover#77]
I noticed that the ideographic space (U+3000) `　` causes the crawler to miscalculate the folder size. Or at least I think that's the crawler is messing up.
If you have a folder that contains an ideographic space, say `単行本の書店特典漫画　その2` it will cause diskover to display the folder size as the total size of all the data.

If I have 100TB of data, that folder will have the size of 100TB.
Any subfolder in tha folder will also be affected by the same bug and will display as 100TB big folder. Be it ascii, utf or unicode folder names.

There are other full width character like `（）`, but I don't know if they also cause problems.

**Comment by shirosaidev** [comment]
please submit a pr with the characters added to **escape_chars** function in **diskover.py**

**Comment by shirosaidev** [comment]
also submit another pr for diskover-web **src/diskover/Diskover.php** **escape_chars** function

**Comment by Suika** [comment]
Ok, after running it with the changes for a few days and exploring the whole thing, there seem to be no problems.
