### ISSUE TITLE
Need help running diskover with linuxserver and docker 

### ISSUE THREAD

**Issue by ovizii** [shirosaidev/diskover#86]
I know this is most probably out of the scope of this forum but I thought I'd try my luck.

https://hub.docker.com/r/linuxserver/diskover/ 

My problem is that I am getting a server error 500 when accessing the diskover GUI. Redis and Elasticsearch seem to work fine. 

Any hints? I also posted in their discourse forum but no reply so far: https://discourse.linuxserver.io/t/linuxserver-diskover-help-cant-access-web-interface/1992/3

The only possibly related error I can find is this one: 

cat config/log/nginx/error.log

```
2020/09/17 10:21:23 [error] 381#381: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Elasticsearch\Common\Exceptions\BadRequest400Exception in /app/diskover-web/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php:630
Stack trace:
#0 /app/diskover-web/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(293): Elasticsearch\Connections\Connection->process4xxError(Array, Array, Array)
#1 /app/diskover-web/vendor/react/promise/src/FulfilledPromise.php(28): Elasticsearch\Connections\Connection->Elasticsearch\Connections\{closure}(Array)
#2 /app/diskover-web/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
#3 /app/diskover-web/vendor/guzzlehttp/ringphp/src/Core.php(341): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#4 /app/diskover-web/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Connections/Connection.php(314): GuzzleHttp\Ring\Core::proxy(Object(GuzzleHttp\Ring\Future\" while reading response header from upstream, client: 192.168.178.141, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.178.140:3080"
```

**Comment by doubleailes** [comment]
DIdi you fix the memory issue of elastic:
https://github.com/docker-library/elasticsearch/issues/111

**Comment by ovizii** [comment]
thanks. I read through the thread you linked and I had followed these instructions so that shouldn't be the problem:

_ElasticSearch also requires a sysctl setting on the host machine to run properly. Running sysctl -w vm.max_map_count=262144 will solve this issue. To make this setting persistent through reboots, set this value in /etc/sysctl.conf_

elasticsearch has these env parameters so I tried going down to 1G and it did not change anything.

```
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"

```

Any more ideas? Like I said, Redis and elsaticsearch seem to work, just the diskover frontend gives an error 500

**Comment by shirosaidev** [comment]
Seems to be an issue with elasticsearch connection from diskover-web (BadRequest400Exception). Maybe try clearing your cookies/browser cache for diskover-web site and reload the browser. It could be an old index set in cookie that no longer exists. Also check the diskover-web config has the correct ip/host set for ES that is resolvable from diskover-web host. https://github.com/shirosaidev/diskover-web/wiki/Getting-Started

**Comment by ovizii** [comment]
thanks for chiming in. I'm pretty sure its not the cookies, I have just tried a couple of other browsers which I have never used before and deleted cookies too. 

Anyway, I know this is not related to diskover, I'm pretty sure they guys over at linuxserver could probably help out but there's still no reply on that side :-(

diskover-web config:

I have passed on the config via environmental variables like this:
```
    environment:
      - ES_HOST=diskover_elasticsearch
      - ES_PORT=9200
      - ES_USER=elastic
      - ES_PASS=secretpass
```
and I have just checked config/diskover.cfg and they match:
```
[elasticsearch]
host = diskover_elasticsearch
port = 9200
user = elastic
password = secretpass
```

Constants.php also reflects the same values:
```
namespace diskover;

class Constants {
    // set to your Elasticsearch host or ip, if you are using AWS set to your endpoint without http:// or https://
    const ES_HOST = 'diskover_elasticsearch';
    // set to your Elasticsearch port, default 9200, if you are using AWS set to 443 or 80
    const ES_PORT = 9200;
    // set to TRUE if using AWS ES
    const AWS = FALSE;
    // set to TRUE if using AWS ES and HTTPS, FALSE FOR HTTP
    const AWS_HTTPS = TRUE;
    // set following two lines if using X-Pack http-auth
    const ES_USER = 'elastic';
    const ES_PASS = 'secretpass';
    // login auth for diskover-web
    const LOGIN_REQUIRED = FALSE;
    const DISKOVER_USER = 'diskover';
    const DISKOVER_PASS = 'darkdata';

```

I have already stopped diskover, redis and elasticsearch then deleted all files created by this docker-compose.yml file and restarted the stack, just to make sure none of the config got messed up but it didn't help.

The hostname works, as I can enter the diskover container and ping it:
```
docker exec -ti diskover bash
ping diskover_elasticsearch
PING diskover_elasticsearch (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.074 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.071 ms
64 bytes from 172.18.0.3: seq=2 ttl=64 time=0.078 ms
```
everything inside the diskover container seem to be listening properly where they are supposed to:
```
root@diskover:/# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      348/nginx.conf
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      348/nginx.conf
tcp        0      0 0.0.0.0:9181            0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.11:41159        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      356/php-fpm.conf)
udp        0      0 127.0.0.11:35181        0.0.0.0:*             
```
things work, as the elasticsearch grows bigger, its just that the web gui doesn't work:
```
du -cksh *
439K    config
50K     data
8.5K    docker-compose.yml
903M    elasticsearch
25K     redis
904M    total

```

**Comment by LambdaDriver** [comment]
I ran into the same issue. Make sure your elasticsearch data directory is owned by user ID `1000`. 

This would be a good opportunity to expose an error page if elasticsearch is unreachable or health is red.

**Comment by ovizii** [comment]
I was pretty sure I had the right permissions, nevertheless, I started again from scratch and now I get:

```
 at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.9.jar:5.6.9]        │
│    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.9.jar:5.6.9]         │
│    at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.9.jar:5.6.   │
│   9]                                                                                                          │
│    ... 6 more                                                                                                 │
│   Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes  
```

The funny issue is, I had set the folder: elasticsearch to be owned by 1000:1000 then started the containers. I ended up with a folder named data inside of elasticsearch owned by root - which was created by these containers. I have now reset perms to 1000:1000 


```
ls -al
total 108
drwxrwx---  6             1000 1000    7 Nov  1 16:27 .
drwxrwxrwx 26               82 root   26 Oct 30 13:39 ..
drwxrwx---  8             1000 1000   14 Nov  1 16:27 config
drwxrwx---  3             1000 1000    3 Nov  1 16:27 data
-rwxrwx---  1             1000 1000 2077 Oct 21 12:17 docker-compose.yml
drwxrwx---  3             1000 1000    3 Nov  1 16:27 elasticsearch
drwxrwx---  2 systemd-coredump 1000    2 Nov  1 16:26 redis
root@nas:/sixer/docker/diskover# ls -al elasticsearch/
total 50
drwxrwx--- 3 1000 1000 3 Nov  1 16:27 .
drwxrwx--- 6 1000 1000 7 Nov  1 16:27 ..
drwxr-xr-x 2 root root 2 Nov  1 16:27 data
root@nas:/sixer/docker/diskover# ls -al elasticsearch/data/
total 33
drwxr-xr-x 2 root root 2 Nov  1 16:27 .
drwxrwx--- 3 1000 1000 3 Nov  1 16:27 ..

```

restarted the elasticsearch container and now I get this error:

```
[2020-11-01T15:32:04,613][WARN ][o.e.x.s.a.AuthenticationService] [yK30Evc] An error occurred while attem   │
│   pting to authenticate [elastic] against realm [reserved] - ElasticsearchSecurityException[failed to authe   │
│   nticate user [elastic]]  
```

On  a hunch I changed the password inside my docker-compose.yml file back tpo the default "changeme" and things work now - I can access the web interface.

`      - ES_PASS=changeme`

will post again once a crawl has run:

![image](https://user-images.githubusercontent.com/837902/97807430-fbb03780-1c60-11eb-9967-464d05cd6953.png)

**Comment by ovizii** [comment]
ok, I am finally seeing data, seems one crawl has finished. Will close this but imho the instructions of the linuxserver docker container are a mess.

thanks everyone for helping out even though I am still running with the default "changeme" password :-(
